import tkinter as tk
import random
mwindow=tk.Tk()
mwindow.title("随机数")
mwindow.iconphoto(True,tk.PhotoImage(file='icon.png'))
lbl1=tk.Label(mwindow,text="请输入最小范围：")
ent1=tk.Entry(mwindow,width=40)
lbl2=tk.Label(mwindow,text="请输入最大范围：")
ent2=tk.Entry(mwindow,width=40)
lbl3=tk.Label(mwindow,text="       ")
lbl1.grid(column=0,row=0)
ent1.grid(column=1,row=0)
lbl2.grid(column=0,row=1)
ent2.grid(column=1,row=1)
def rd():
    rdm1=ent1.get()
    rdm2=ent2.get()
    rdm1=int(rdm1)
    rdm2=int(rdm2)
    rdm3=random.randint(rdm1,rdm2)
    rdm3=str(rdm3)
    lbl3.configure(text="结果为"+rdm3)
    lbl3.grid(column=1,row=2)
btn1=tk.Button(mwindow,text="开始",command=rd)
btn1.grid(column=0,row=2)
mwindow.mainloop()